# Generated by Django 5.2.7 on 2025-10-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('after_grade12_questions', 'Aptitude test'), ('uniStudents_questions', 'University Student'), ('combined_questions', 'Both Grade 12 and University Students')], max_length=200)),
                ('responses', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
