# Generated by Django 5.2.7 on 2025-10-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NovaX_webpage', '0002_surveyanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyAnswer',
        ),
    ]
