# Generated by Django 5.2.7 on 2025-10-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovaX_webpage', '0003_delete_surveyanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careersurvey',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
