# Generated by Django 5.2.7 on 2025-10-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovaX_webpage', '0004_alter_careersurvey_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('established', models.IntegerField()),
                ('description', models.TextField()),
                ('about', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
